services:
  # Ana uygulama - Express + React (frontend)
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network
      
  # Backend servisi
  backend:
    build: ./bulduk-be
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 