services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:8000

  backend:
    build: ./bulduk-be
    ports:
      - "8000:8000"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8000
    depends_on:
      - backend 